import type { Metadata } from "next";
import { Syne, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} ${inter.variable} antialiased font-inter`}
      >
        <SessionProvider>
          <Toaster richColors position="top-center" duration={2000} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
